# 使用官方Python运行时作为父镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 将当前目录内容复制到容器中的/app
COPY . /app

# 安装项目依赖
RUN pip install --no-cache-dir fastapi uvicorn
RUN pip install --no-cache-dir jinja2

# 如果您有requirements.txt文件,请使用下面这行替换上面的RUN命令
# RUN pip install --no-cache-dir -r requirements.txt

# 让端口80在容器外可用
EXPOSE 80

# 定义环境变量
ENV NAME World

# 在容器启动时运行app.py
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]