   name: Deploy FastAPI to Aliyun using Docker

   on:
     push:
       branches: [main] # 或者你希望触发部署的分支

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}

         - name: Build and push Docker image
           uses: docker/build-push-action@v2
           with:
             context: .
             file: ./Dockerfile
             push: true
             tags: ${{ secrets.DOCKER_USERNAME }}/your-fastapi-app:latest

         - name: Deploy via SSH
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.SSH_HOST }}
             port: ${{ secrets.SSH_PORT }}
             username: ${{ secrets.SSH_USER }}
             key: ${{ secrets.DEPLOY_SSH_KEY }}
             script: |
               # 在这里放置部署脚本
               sudo docker pull ${{ secrets.DOCKER_USERNAME }}/your-fastapi-app:latest
               sudo docker stop $(sudo docker ps -aq --filter "name=your-fastapi-app") || true
               sudo docker rm $(sudo docker ps -aq --filter "name=your-fastapi-app") || true
               sudo docker run -d --name your-fastapi-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/your-fastapi-app:latest