name: Deploy fakeBBS to HUAWEI CLOUD using Docker

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      runner:
        description: 'Specify the runner to use'
        required: true
        default: 'self-hosted'
        type: choice
        options:
          - self-hosted


jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: fakeBBS:latest

      - name: Stop existing Docker container
        run: docker stop fakeBBS || true

      - name: Remove existing Docker container
        run: docker rm fakeBBS || true

      - name: Run new Docker container
        run: docker run -d --name fakeBBS -p 8000:80 fakeBBS:latest
